@startuml

Пользователь -> "Телеграмм бот": Отправляет вопрос
"Телеграмм бот" -> "Сервис RAG": Отправляет запрос
"Сервис RAG" -> ChromaDB: Ищем по базе знаний
ChromaDB -> "Сервис RAG": Получем список документов
"Сервис RAG" -> LLM: Формируем ответ
LLM -> "Сервис RAG": Получаем ответ
"Сервис RAG" -> "Телеграмм бот": Получает ответ
"Телеграмм бот" -> Пользователь: Получает ответ

@enduml